# Generated by Django 4.1 on 2023-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_owner_table_otp1_owner_table_otp_used1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_type',
            field=models.IntegerField(default=0),
        ),
    ]
