# Generated by Django 4.1 on 2023-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='e_con',
            field=models.CharField(max_length=13),
        ),
    ]
