# Generated by Django 4.1 on 2023-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0005_alter_enquiry_e_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='e_mail',
            field=models.EmailField(default=-1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
