# Generated by Django 4.1.7 on 2023-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_enquiry_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_details',
            name='pg_price',
            field=models.IntegerField(max_length=7),
        ),
    ]
