# Generated by Django 4.1.7 on 2023-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_alter_pg_details_pg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_details',
            name='pg_price',
            field=models.IntegerField(),
        ),
    ]
